//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANQUYEN
    {
        public int MaPQ { get; set; }
        public int MaQL { get; set; }
        public bool QL_Admin { get; set; }
        public bool QL_NhaCungCap { get; set; }
        public bool QL_SanPham { get; set; }
        public bool QL_ThuongHieu { get; set; }
        public bool QL_LoaiGiay { get; set; }
        public bool QL_DonHang { get; set; }
        public bool QL_KhachHang { get; set; }
        public bool QL_YKienKhachHang { get; set; }
    
        public virtual QUANLY QUANLY { get; set; }
    }
}
