//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINNHAN
    {
        public int MaTinNhan { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaQL { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime ThoiGianGui { get; set; }
        public bool DaDoc { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual QUANLY QUANLY { get; set; }
    }
}
